char tablero[31][29]={
    {"xxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
    {"xccccccccccccxxccccccccccccx"},
    {"xcxxxxcxxxxxcxxcxxxxxcxxxxcx"},
    {"xcx  xcx   xcxxcx   xcx  xcx"},
    {"xcxxxxcxxxxxcxxcxxxxxcxxxxcx"},
    {"xccccccccccccccccccccccccccx"},
    {"xcxxxxcxxcxxxxxxxxcxxcxxxxcx"},
    {"xcxxxxcxxcxxxxxxxxcxxcxxxxcx"},
    {"xccccccxxccccxxccccxxccccccx"},
    {"xxxxxxcxxxxxcxxcxxxxxcxxxxxx"},
    {"     xcxxxxxcxxcxxxxxcx     "},
    {"     xcxx          xxcx     "},
    {"     xcxx xxx  xxx xxcx     "},
    {"xxxxxxcxx x      x xxcxxxxxx"},
    {"  f   c   x      x   c  f   "},
    {"xxxxxxcxx x      x xxcxxxxxx"},
    {"     xcxx xxxxxxxx xxcx     "},
    {"     xcxx    p     xxcx     "},
    {"     xcxx xxxxxxxx xxcx     "},
    {"xxxxxxcxxfxxxxxxxxfxxcxxxxxx"},
    {"xccccccccccccxxccccccccccccx"},
    {"xcxxxxcxxxxxcxxcxxxxxcxxxxcx"},
    {"xcxxxxcxxxxxcxxcxxxxxcxxxxcx"},
    {"xcccxxccccccccccccccccxxcccx"},
    {"xxxcxxcxxcxxxxxxxxcxxcxxcxxx"},
    {"xxxcxxcxxcxxxxxxxxcxxcxxcxxx"},
    {"xccccccxxccccxxccccxxccccccx"},
    {"xcxxxxxxxxxxcxxcxxxxxxxxxxcx"},
    {"xcxxxxxxxxxxcxxcxxxxxxxxxxcx"},
    {"xccccccccccccccccccccccccccx"},
    {"xxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
};
